all:
  # DEBUG:1 | INFO:2 | WARNING:4 | ERROR:8 | CRITICAL:16
  debug_logging_level: 31
  normal_logging_level: 28

  debug:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: debug.log
  info:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: debug.log
  warning:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: error.log
  error:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: error.log
  critical:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: error.log
  fatal:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: fatal.log
  kpi:
    socket: unix:///var/run/td-agent/td-agent.sock
#    # host: localhost
#    # port: 24224
