all:
  base_uri: 
  timer:
    timezone: Asia/Tokyo
    application_reset_time: 00:00:00
  logger_config_file: First_logger.yml
  database_config_file: First_database.yml
  apcu_config_file: First_apcu.yml
  memcache_config_file: First_memcache.yml
  redis_config_file: First_redis.yml
  filter_config_file: First_filter.yml
  autoload:
    - %%CONTEXT_ROOT%%/projects/First/models
    - %%CONTEXT_ROOT%%/projects/First/database
local:
  base_uri: phlame.vb/
